[package]
name = "ravac"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rava compiler: Java syntax, Rust semantics. Transpiles .rava to Rust."

[[bin]]
name = "ravac"
path = "src/main.rs"

[dev-dependencies]
rava-check.workspace = true
rava-build.workspace = true

[dependencies]
rava-ast.workspace = true
rava-lexer.workspace = true
rava-parser.workspace = true
rava-codegen.workspace = true
rava-check.workspace = true
rava-build.workspace = true
