[package]
name = "rava-build"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Projets Rava : paquets, arborescence de modules, Cargo.toml généré."

[dependencies]
rava-ast.workspace = true
rava-parser.workspace = true
rava-codegen.workspace = true
